KP-839 [CodeBuild] method Stop Build param Build autocomplete shows builds that are NOT in progress
Kaholo/kaholo-plugin-aws-code-build pull request #7
Opened 2022-07-08 14:02 UTC by xkcm

[**KP-839 in Jira**](https://kaholo.atlassian.net/browse/KP-839)

2022-07-11 07:06 UTC, graddaniel requested changes

2022-07-11 07:06 UTC, graddaniel commented on autocomplete.js
> +    const mappedAutocompleteItems = fetchResult.map((fetchedItem) => (
`Array.map` accepts functions and `awsPluginLibrary.autocomplete.toAutocompleteItemFromPrimitive` is a function already.

2022-07-11 07:06 UTC, graddaniel commented on code-commit-list-functions.js
> +  ).catch((error) => {
Don't mix promise with async/await approach. The latter is what we agreed to use at plugins and its way of handling errors is a try-catch block.

2022-07-11 09:39 UTC, graddaniel approved these changes

2022-07-12 09:18 UTC, kenskyfish approved these changes
Tested, works correctly.

2022-07-12 09:33 UTC, merged